Remove namespace from controller-manager-alerts-monitor
This line is causing:

Error: Value controller-manager-alerts-monitor: error validating object:
metadata.namespace: Forbidden: not allowed on this type.

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>